name: test

on:
  pull_request:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  forge-test:
    name: Run Forge Tests and Checks 
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.8'

      - name: Install eth-abi
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install eth-abi

      - name: Install Foundry
        uses: step-security/foundry-toolchain@799252b03ddc2194cbaa4a948909d9ca752e7267 # v1.7.0
        with:
          version: stable

      - name: Run Forge build
        run: |
          forge --version
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --ffi
        id: test

      - name: Check formatting
        run: |
          forge fmt --check
        id: fmt
